fadecandy:
  address: localhost
  port: 7890
  pin: 0
  pixelCount: 9
  interpolate: true
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:file:./db/pixels
  jpa:
    hibernate:
      ddl-auto: update